### ISSUE TITLE
Product Module-Add Product

### ISSUE THREAD

**Issue by jaleela9502** [fssa-batch3/sec_c_sec_c_jaleela.badhurudeen__corejava_project_2#1]
- [ ] Product Model
- [ ] Product DAO- addProduct
- [ ] Product Service - addProduct
- [ ] Product Validator

**Comment by msbAtGit** [comment]
- [ ] Check the spelling of model class attributes.
- [ ] Use javadoc comments
- [ ] Adding check constraint for enum data type attribute
- [ ] ServiceException which will the Validation exception and rethrow as ServiceException
- [ ] Logger should be in service layer not in DAO Layer
- [ ] Dao layer should throw DAO Exception
- [ ] Add TODOs if you are adding print statements for debugging. Remove the print statements once the code works
